"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:bright-black)\
$os\
$username\
[](fg:green bg:bright-black)\
$directory\
[](fg:green bg:blue)\
$git_branch\
$git_status\
[](fg:blue bg:cyan)\
$c\
$cpp\
$golang\
$java\
$kotlin\
$kubernetes\
$lua\
$nodejs\
$python\
$rlang\
$ruby\
$rust\
[](fg:cyan bg:bright-black)\
$character\
[ ](fg:bright-black)
"""

right_format = """
[](fg:bright-black)\
$time\
$battery\
[](fg:bright-black)
"""

[time]
disabled = false
time_format = '%R'
format = '[$time](bg:bright-black fg:blue)'

[directory]
format = "[ $path ](fg:bright-black bg:green)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[username]
show_always = true
style_user = "fg:white bg:bright-black"
format = "[ $user ]($style)"

[git_branch]
symbol = ""
format = '[[ $symbol $branch ](fg:bright-black bg:blue)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:bright-black bg:blue)]($style)'

[character]
success_symbol = '[ \$](fg:white bg:bright-black)'
error_symbol = '[ !](fg:red bg:bright-black)'
vimcmd_symbol = '[ ](fg:white bg:bright-black)'
vimcmd_replace_one_symbol = '[ ](fg:white bg:bright-black)'
format = "$symbol"

# Programming languages

[c]
format = '[  ](fg:bright-black bg:cyan)'

[cpp]
format = '[  ](fg:bright-black bg:cyan)'

[golang]
format = '[  ](fg:bright-black bg:cyan)'

[java]
format = '[  ](fg:bright-black bg:cyan)'

[kotlin]
format = '[  ](fg:bright-black bg:cyan)'

[kubernetes]
format = '[  ](fg:bright-black bg:cyan)'

[lua]
format = '[ 󰢱 ](fg:bright-black bg:cyan)'

[nodejs]
format = '[  ](fg:bright-black bg:cyan)'

[python]
format = '[  ](fg:bright-black bg:cyan)'

[rlang]
format = '[  ](fg:bright-black bg:cyan)'

[ruby]
format = '[  ](fg:bright-black bg:cyan)'

[rust]
format = '[  ](fg:bright-black bg:cyan)'

# Battery status

[battery]
disabled = false

[[battery.display]]
threshold = 10
style = 'bold red'

[[battery.display]]
threshold = 30
style = 'bold yellow'
