"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:green)\
$username\
[](bg:yellow fg:green)\
$directory\
[](fg:yellow bg:cyan)\
$git_branch\
$git_status\
[](fg:cyan bg:bright-black)\
$character\
[ ](fg:bright-black)
"""

right_format = """
[](fg:bright-black)\
$time\
[](fg:bright-black)
"""

[time]
disabled = false
time_format = '%R'
format = '[$time](bg:bright-black fg:green)'

[directory]
format = "[ $path ](fg:bright-black bg:yellow)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[username]
show_always = true
style_user = "fg:bright-black bg:green"
format = "[ $user ]($style)"

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:bright-black bg:cyan)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:bright-black bg:cyan)]($style)'

[character]
success_symbol			= '[ \$](fg:white bg:bright-black)'
error_symbol			= '[ !](fg:red bg:bright-black)'
vimcmd_symbol			= '[ ](fg:white bg:bright-black)'
vimcmd_replace_one_symbol	= '[ ](fg:white bg:bright-black)'
format = "$symbol"
