# preload = /home/nilbog/Pictures/Wallpapers/tokyo02.jpg
# wallpaper = DP-1, /home/nilbog/Pictures/Wallpapers/tokyo02.jpg
wallpaper {
	monitor = DP-3
	path = /home/nilbog/Pictures/Wallpapers/tokyo02.jpg
	fit_mode = cover
}

wallpaper {
	monitor = DP-2
	path = /home/nilbog/Pictures/Wallpapers/tokyo01.jpg
	fit_mode = cover
}

wallpaper {
	monitor = HDMI-A-1
	path = /home/nilbog/Pictures/Wallpapers/tokyo03.jpg
	fit_mode = cover
}

	splash = false

