# vim:ft=kitty

## name:     Nord Light
## author:   Arctic Ice Studio / nilbog
## blurb:    An arctic, north-bluish clean and elegant light theme

# The basic colors (Snow Storm palette)
foreground            #2E3440
background            #ECEFF4
selection_foreground  #ECEFF4
selection_background  #4C566A

# Cursor colors
# Using Nord Blue (Nord 9)
cursor                #81A1C1
cursor_text_color     #ECEFF4

# URL color (Nord 8)
url_color               #88C0D0

# Kitty window border colors
active_border_color     #81A1C1
inactive_border_color   #D8DEE9

# Tab bar colors
active_tab_foreground   #ECEFF4
active_tab_background   #81A1C1
inactive_tab_foreground #4C566A
inactive_tab_background #E5E9F0

# The 16 terminal colors

# black (Using Nord 0-3 for depth)
color0 #ECEFF4
color8 #D8DEE9

# red (Nord 11)
color1 #BF616A
color9 #BF616A

# green (Nord 14)
color2  #A3BE8C
color10 #A3BE8C

# yellow (Nord 13)
color3  #EBCB8B
color11 #EBCB8B

# blue (Nord 9)
color4  #81A1C1
color12 #81A1C1

# magenta (Nord 15)
color5  #B48EAD
color13 #B48EAD

# cyan (Nord 8/7)
color6  #88C0D0
color14 #8FBCBB

# white (Using Nord 3/4 for high-contrast text)
color7  #4C566A
color15 #2E3440
