# vim:ft=kitty

## name:     BogOS Dark
## author:   nilbog
## blurb:    Custom theme for BogOS ricing

# The basic colors
foreground              #a5a296
background              #1D2230
selection_foreground    #1D2230
selection_background    #a5a296

# Cursor colors
# Using 'primary' (green) for the cursor
cursor                  #80a961
cursor_text_color       #1D2230

# URL color when hovering with mouse
url_color               #6ba2c4

# Kitty window border colors
active_border_color     #80a961
inactive_border_color   #282e3f

# Tab bar colors
active_tab_foreground   #1D2230
active_tab_background   #80a961
inactive_tab_foreground #a5a296
inactive_tab_background #282e3f

# The 16 terminal colors

# black (background/black)
color0 #1D2230
color8 #282e3f

# red
color1 #c46b6b
color9 #c46b6b

# green
color2  #80a961
color10 #80a961

# yellow
color3  #D9B36C
color11 #D9B36C

# blue
color4  #394260
color12 #394260

# magenta
color5  #7E6BC4
color13 #7E6BC4

# cyan
color6  #6ba2c4
color14 #6ba2c4

# white
color7  #a5a296
color15 #EAE6DA
